#!/usr/bin/env python3
"""
Convert LightGBM models to ONNX format for C++ inference.
Only converts Level 1-5 models (Level 0 and Level 6 don't need prediction).
"""

import os
import sys
import pickle
import json
import numpy as np
from pathlib import Path

try:
    import lightgbm as lgb
except ImportError:
    print("ERROR: lightgbm not installed. Run: pip install lightgbm")
    sys.exit(1)

try:
    from onnxmltools import convert_lightgbm
    from onnxmltools.convert.common.data_types import FloatTensorType
except ImportError:
    print("ERROR: onnxmltools not installed. Run: pip install onnxmltools")
    sys.exit(1)

try:
    import onnx
except ImportError:
    print("ERROR: onnx not installed. Run: pip install onnx")
    sys.exit(1)


def convert_models(models_dir: str, output_dir: str = None):
    """
    Convert LightGBM models to ONNX format.
    
    Args:
        models_dir: Directory containing model_level_{1-5}_lgb.txt files
        output_dir: Output directory for ONNX models (default: same as models_dir)
    """
    models_path = Path(models_dir)
    output_path = Path(output_dir) if output_dir else models_path
    output_path.mkdir(parents=True, exist_ok=True)
    
    print(f"Input directory: {models_path}")
    print(f"Output directory: {output_path}")
    print()
    
    converted = []
    
    for level in range(1, 6):  # Level 1-5 only
        lgb_file = models_path / f"model_level_{level}_lgb.txt"
        onnx_file = output_path / f"model_level_{level}.onnx"
        
        if not lgb_file.exists():
            print(f"[Level {level}] SKIP: {lgb_file} not found")
            continue
        
        print(f"[Level {level}] Converting {lgb_file.name}...")
        
        try:
            # Load LightGBM model from text file
            with open(lgb_file, 'r') as f:
                model_str = f.read()
            model = lgb.Booster(model_str=model_str)
            
            # Get model info
            num_trees = model.num_trees()
            num_features = model.num_feature()
            print(f"  - Trees: {num_trees}, Features: {num_features}")
            
            # Define input type (batch_size=None for dynamic, 69 features)
            initial_type = [('features', FloatTensorType([None, 69]))]
            
            # Convert to ONNX
            onnx_model = convert_lightgbm(
                model, 
                initial_types=initial_type,
                target_opset=12  # Use opset 12 for compatibility
            )
            
            # Save ONNX model
            onnx.save(onnx_model, str(onnx_file))
            
            # Verify the saved model
            onnx_model_loaded = onnx.load(str(onnx_file))
            onnx.checker.check_model(onnx_model_loaded)
            
            file_size = onnx_file.stat().st_size / 1024  # KB
            print(f"  - Saved: {onnx_file.name} ({file_size:.1f} KB)")
            converted.append(level)
            
        except Exception as e:
            print(f"  - ERROR: {e}")
            import traceback
            traceback.print_exc()
    
    print()
    print(f"Converted {len(converted)} models: Level {converted}")
    return converted


def export_scaler_params(models_dir: str, output_file: str):
    """
    Export StandardScaler parameters (mean_ and scale_) to C++ header file.
    
    Args:
        models_dir: Directory containing scaler_level_{1-5}.pkl files
        output_file: Output C++ header file path
    """
    models_path = Path(models_dir)
    
    print(f"Exporting scaler parameters to {output_file}")
    
    scalers = {}
    
    for level in range(1, 6):  # Level 1-5 only
        scaler_file = models_path / f"scaler_level_{level}.pkl"
        
        if not scaler_file.exists():
            print(f"[Level {level}] SKIP: {scaler_file} not found")
            continue
        
        with open(scaler_file, 'rb') as f:
            scaler = pickle.load(f)
        
        if not hasattr(scaler, 'mean_') or not hasattr(scaler, 'scale_'):
            print(f"[Level {level}] ERROR: Invalid scaler (no mean_/scale_)")
            continue
        
        scalers[level] = {
            'mean': scaler.mean_.tolist(),
            'scale': scaler.scale_.tolist()
        }
        print(f"[Level {level}] mean shape: {scaler.mean_.shape}, scale shape: {scaler.scale_.shape}")
    
    # Generate C++ header file
    with open(output_file, 'w') as f:
        f.write("// Auto-generated by convert_lgb_to_onnx.py\n")
        f.write("// StandardScaler parameters for Level 1-5 models\n")
        f.write("#pragma once\n\n")
        f.write("#include <array>\n")
        f.write("#include <unordered_map>\n\n")
        f.write("namespace ROCKSDB_NAMESPACE {\n\n")
        f.write("constexpr size_t kNumFeatures = 69;\n\n")
        
        # Write mean arrays
        for level in range(1, 6):
            if level not in scalers:
                continue
            mean = scalers[level]['mean']
            f.write(f"constexpr double kScalerMeanLevel{level}[kNumFeatures] = {{\n")
            for i in range(0, len(mean), 5):
                chunk = mean[i:i+5]
                f.write("    " + ", ".join(f"{v:.15e}" for v in chunk))
                if i + 5 < len(mean):
                    f.write(",")
                f.write("\n")
            f.write("};\n\n")
        
        # Write scale arrays
        for level in range(1, 6):
            if level not in scalers:
                continue
            scale = scalers[level]['scale']
            f.write(f"constexpr double kScalerScaleLevel{level}[kNumFeatures] = {{\n")
            for i in range(0, len(scale), 5):
                chunk = scale[i:i+5]
                f.write("    " + ", ".join(f"{v:.15e}" for v in chunk))
                if i + 5 < len(scale):
                    f.write(",")
                f.write("\n")
            f.write("};\n\n")
        
        # Write helper function to get scaler params by level
        f.write("inline const double* GetScalerMean(int level) {\n")
        f.write("    switch (level) {\n")
        for level in range(1, 6):
            if level in scalers:
                f.write(f"        case {level}: return kScalerMeanLevel{level};\n")
        f.write("        default: return nullptr;\n")
        f.write("    }\n")
        f.write("}\n\n")
        
        f.write("inline const double* GetScalerScale(int level) {\n")
        f.write("    switch (level) {\n")
        for level in range(1, 6):
            if level in scalers:
                f.write(f"        case {level}: return kScalerScaleLevel{level};\n")
        f.write("        default: return nullptr;\n")
        f.write("    }\n")
        f.write("}\n\n")
        
        f.write("}  // namespace ROCKSDB_NAMESPACE\n")
    
    print(f"Exported scaler params for {len(scalers)} levels")
    return list(scalers.keys())


def verify_conversion(models_dir: str, onnx_dir: str = None):
    """
    Verify ONNX models produce same results as LightGBM models.
    """
    import onnxruntime as ort
    
    models_path = Path(models_dir)
    onnx_path = Path(onnx_dir) if onnx_dir else models_path
    
    print("\nVerifying ONNX conversion accuracy...")
    
    # Create random test features
    np.random.seed(42)
    test_features = np.random.rand(10, 69).astype(np.float32)
    
    for level in range(1, 6):
        lgb_file = models_path / f"model_level_{level}_lgb.txt"
        onnx_file = onnx_path / f"model_level_{level}.onnx"
        scaler_file = models_path / f"scaler_level_{level}.pkl"
        
        if not lgb_file.exists() or not onnx_file.exists():
            continue
        
        print(f"\n[Level {level}] Comparing predictions...")
        
        # Load LightGBM model
        with open(lgb_file, 'r') as f:
            lgb_model = lgb.Booster(model_str=f.read())
        
        # Load scaler
        with open(scaler_file, 'rb') as f:
            scaler = pickle.load(f)
        
        # Scale features
        scaled_features = scaler.transform(test_features).astype(np.float32)
        
        # LightGBM prediction
        lgb_pred = lgb_model.predict(scaled_features)
        
        # ONNX prediction
        sess = ort.InferenceSession(str(onnx_file))
        input_name = sess.get_inputs()[0].name
        onnx_pred = sess.run(None, {input_name: scaled_features})[0].flatten()
        
        # Compare
        max_diff = np.max(np.abs(lgb_pred - onnx_pred))
        mean_diff = np.mean(np.abs(lgb_pred - onnx_pred))
        
        print(f"  - Max diff: {max_diff:.10f}")
        print(f"  - Mean diff: {mean_diff:.10f}")
        print(f"  - LGB sample: {lgb_pred[:3]}")
        print(f"  - ONNX sample: {onnx_pred[:3]}")
        
        if max_diff < 1e-5:
            print(f"  - PASS: Predictions match!")
        else:
            print(f"  - WARNING: Predictions differ (max_diff={max_diff})")


if __name__ == '__main__':
    # Default paths
    default_models_dir = "/home/usr/test_environment/workplace/log/experiment_logs/new_log/run_batch_20260131_063807/backup_old_data_models/models"
    default_output_dir = "/home/usr/test_environment/rocksdb/models_onnx"
    default_scaler_header = "/home/usr/test_environment/rocksdb/db/scaler_params.h"
    
    models_dir = sys.argv[1] if len(sys.argv) > 1 else default_models_dir
    output_dir = sys.argv[2] if len(sys.argv) > 2 else default_output_dir
    scaler_header = sys.argv[3] if len(sys.argv) > 3 else default_scaler_header
    
    print("=" * 60)
    print("LightGBM to ONNX Conversion Tool")
    print("=" * 60)
    print()
    
    # Step 1: Convert models
    converted = convert_models(models_dir, output_dir)
    
    # Step 2: Export scaler params
    print()
    print("=" * 60)
    exported = export_scaler_params(models_dir, scaler_header)
    
    # Step 3: Verify conversion
    print()
    print("=" * 60)
    verify_conversion(models_dir, output_dir)
    
    print()
    print("=" * 60)
    print("Done!")
    print(f"ONNX models: {output_dir}")
    print(f"Scaler header: {scaler_header}")
